import {StyleSheet} from 'react-native';
import {colors, sizes, fontSize} from '../../services';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    // backgroundColor: '#fff',
  },
  imageContainer: {
    alignItems: 'center',
    position: 'relative',
  },
  profileImage: {
    width: sizes.screenWidth,
    height: sizes.screenHeight * 0.4,
    resizeMode: 'cover',
  },
  scrollView: {
    marginTop: -sizes.screenHeight * 0.05,
    borderTopLeftRadius: sizes.screenWidth * 0.1,
    borderTopRightRadius: sizes.screenWidth * 0.1,
    backgroundColor: colors.white,
    overflow: 'hidden',
  },
  scrollContainer: {
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  idSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginVertical: 10,
    paddingHorizontal: 10,
  },
  idText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#555',
  },
  premiumBadge: {
    backgroundColor: colors.btnBg,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 5,
    alignSelf: 'flex-start',
  },
  premiumText: {
    color: colors.white,
    textTransform: 'uppercase',
    fontSize: fontSize.small,
    fontWeight: '600',
  },
  timeSection: {
    alignSelf: 'flex-start',
    marginBottom: 10,
    backgroundColor: '#A5F58A',
    paddingRight: sizes.screenWidth * 0.02,
    paddingLeft: sizes.screenWidth * 0.02,
    padding: sizes.screenHeight * 0.01,
    borderRadius: sizes.screenWidth * 0.02,
  },
  activeTime: {
    color: colors.black,
  },
  menuSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    alignSelf: 'center',
    marginVertical: 20,
    width: sizes.screenWidth * 0.6,
  },
  menuButton: {
    alignItems: 'center',
    justifyContent: 'center',
    width: sizes.screenWidth * 0.25,
    borderRadius: 5,
  },
  menuText: {
    fontSize: 16,
    color: colors.grayText,
    fontWeight: '500',
    textAlign: 'center',
    marginTop: 5,
  },
  section: {
    width: '100%',
    marginBottom: 15,
    paddingHorizontal: 10,
  },
  sectionHeader: {
    fontWeight: 'bold',
    marginBottom: 5,
    fontSize: 16,
    color: '#E8CD96',
  },
  sectionText: {
    fontSize: 14,
    color: colors.grayText,
    marginBottom: 3,
    fontWeight: '500',
  },
  buttonSection: {
    width: '100%',
    marginVertical: 20,
    paddingHorizontal: 10,
  },
  actionButton: {
    backgroundColor: colors.blue,
    padding: 10,
    borderRadius: sizes.screenWidth * 0.03,
    marginVertical: 5,
    alignItems: 'center',
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
  },
  greenBorder: {
    borderWidth: 0.3,
    width: sizes.screenWidth * 0.9,
    marginBottom: sizes.screenHeight * 0.01,
    borderColor: colors.border,
    alignSelf: 'center',
  },
  profileIcon: {
    height: sizes.screenHeight * 0.05,
    width: sizes.screenHeight * 0.05,
  },

  whiteBtn: {
    backgroundColor: colors.white,
    padding: 10,
    borderRadius: sizes.screenWidth * 0.03,
    marginVertical: sizes.screenHeight * 0.03,
    alignItems: 'center',
    alignSelf: 'center',
    borderWidth: 1,
    width: sizes.screenWidth * 0.6,
  },
  whiteBtn2:{
    backgroundColor: colors.white,
    padding: 10,
    borderRadius: sizes.screenWidth * 0.03,
    marginVertical: sizes.screenHeight * 0.03,
    alignItems: 'center',
    alignSelf: 'center',
    borderWidth: 1,
  },
  buttonTextBlack: {
    color: colors.black,
    fontSize: fontSize.h5,
    fontWeight: '500',
  },
  modalView: {
    backgroundColor: colors.white,
    borderRadius: sizes.screenWidth * 0.1,
    padding: 20,
    width: sizes.screenWidth * 0.75,
    alignSelf: 'center',
  },

  modalText: {
    color: colors.grayText,
    textAlign: 'center',
    fontSize: fontSize.h5,
    marginBottom: sizes.screenHeight * 0.02,
  },
  bold: {
    fontWeight: '600',
  },
  modalBtn: {
    color: colors.white,
    backgroundColor: '#C0EFBA',
    height: sizes.screenHeight * 0.05,
    borderRadius: sizes.screenWidth * 0.04,
    width: sizes.screenWidth * 0.23,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  btnText: {
    color: colors.grayText,
    fontSize: fontSize.h6,
    fontWeight: '600',
  },
  greenBorderModal: {
    borderWidth: 0.3,
    width: sizes.screenWidth * 0.65,
    marginBottom: sizes.screenHeight * 0.02,
    marginTop: sizes.screenHeight * 0.02,
    borderColor: colors.border,
    alignSelf: 'center',
  },
  logo: {
    height: 68,
    width: 60,
    alignSelf: 'center',
  },
});
